# DigitalOcean App Platform spec
name: hawaiian-lenilani-chatbot
region: sfo3
services:
  - name: web
    environment_slug: python
    github:
      repo: rprovine/hawaiian-lenilani-chatbot
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pip install -r requirements.txt
    run_command: python run_backend.py
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: LEAD_WEBHOOK_URL
        scope: RUN_TIME
        type: SECRET
      - key: LEAD_EMAIL
        scope: RUN_TIME
        value: reno@lenilani.com