name: CI for Hawaiian LeniLani Chatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18.x'
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt
        pip install email-validator
    
    - name: Install Node dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint Python code
      run: |
        pip install flake8 black isort
        # Run linters but don't fail the build
        black --check . || true
        isort --check-only . || true
        flake8 . || true
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    - name: Test Claude Integration
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        if [ -n "$ANTHROPIC_API_KEY" ]; then
          python test_claude.py || echo "Claude test failed"
        else
          echo "Skipping Claude test - no API key"
        fi